services:
  ml_model:
    build:
      context: ml  # Собираем из текущей директории
      dockerfile: Dockerfile  # Используем Dockerfile
    container_name: ml_model
    ports:
      - 8000:8000  # Порт для FastAPI
    environment:
      - MODEL_NAME=${MODEL_NAME}  # Переменные окружения из .env
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}  # Хост внешней ClickHouse
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    depends_on:
      ml_model:
        condition: service_started
    ports:
      - 8080:8080
    volumes:
      - ./backend/cmd/log:/app/backend/cmd/log

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
